import Foundation





/**
 TBD
 
 - Attention:
    Limitations: The keys can only contain \w, -, _ and .
 */
class Config: CustomStringConvertible, CustomDebugStringConvertible {
    
    // MARK: Config-Properties
    
    /// The author's name. Used in content.opf for <dc:creator>.
    var author = ""
    
    /// The book's title. Used in content.opf for <dc:title> and in toc.xhtml for <title>.
    var title = ""
    
    /// The description-text for the book. Used in content.opf for <dc:description>.
    ///
    /// - Remark: As "description" is occupied by Swift's CustomStringConvertible, this is "bookDescription", while the
    ///           related key in the config-file is "description".
    var bookDescription = ""
    
    /// The language-code of the book's language. Used in content.opf for <dc:language>.
    ///
    /// - Remark: This is expected to be an RFC5646 language-code.
    var language = ""
    
    /// The copyright-info for the book. Used in content.opf for <dc:rights>.
    var copyright = ""
    
    /// The book's publication-date. Used in content.opf for <dc:date>.
    ///
    /// - Remark: This is expected to be an ISO8601 date-string.
    var date = ""
    
    /// The book's unique identifier. Used in content.opf for <dc:identifier>.
    var identifier = ""
    
    /// The path (within the package) to the cover-image-file.
    var coverImageFilePath = ""
    
    /// An optional CSS-file to add to generated XHTML-files.
    var style: String? = nil
    
    /// A dictionary mapping content-filenames to toc-entries.
    var tocEntries = [String: String]()
    
    /// An optional filename for the generated epub-file.
    var epubFilename: String? = nil
    
    
    
    
    
    // MARK: - Public
    
    init() {}
    
    init(configDictionary: [String: String]) {
        process(configDictionary: configDictionary)
    }
    
    class func createSampleConfig() -> String {
        var sampleConfig = ""
        
        sampleConfig += "# The author's name. Used in content.opf for <dc:creator>.\n"
        sampleConfig += "author: Ted Tester\n"
        sampleConfig += "\n"
        sampleConfig += "# The language-code of the book's language. Used in content.opf\n"
        sampleConfig += "# for <dc:language>.\n"
        sampleConfig += "language: de-DE\n"
        sampleConfig += "\n"
        sampleConfig += "# The copyright-info for the book. Used in content.opf for <dc:rights>.\n"
        sampleConfig += "copyright: A copyright-hint\n"
        sampleConfig += "\n"
        sampleConfig += "# The book's title. Used in content.opf for <dc:title> and in toc.xhtml\n"
        sampleConfig += "# for <title>\n"
        sampleConfig += "title: The Title Of The Book\n"
        sampleConfig += "\n"
        sampleConfig += "# The book's unique identifier. Used in content.opf for <dc:identifier>\n"
        sampleConfig += "identifier: a.unique.identifier\n"
        sampleConfig += "\n"
        sampleConfig += "# The book's publication-date. Used in content.opf for <dc:date>.\n"
        sampleConfig += "date: 2017-06-01T12:00:00Z\n"
        sampleConfig += "\n"
        sampleConfig += "# The description-text for the book. Used in content.opf for <dc:description>\n"
        sampleConfig += "description: A description-text of the book.\n"
        sampleConfig += "\n"
        sampleConfig += "# The path (within the package) to the cover-image-file.\n"
        sampleConfig += "cover: cover.jpg\n"
        sampleConfig += "\n"
        sampleConfig += "# An optional CSS-file to add to all generated XHTML-files.\n"
        sampleConfig += "style: style.css\n"
        sampleConfig += "\n"
        sampleConfig += "# A list of mappings from content-files (.xhtml or .md) to titles in the\n"
        sampleConfig += "# EPUB's table of contents (toc.xhtml)\n"
        sampleConfig += "01-cover.md: Cover\n"
        sampleConfig += "02-title.md: Title\n"
        sampleConfig += "03-imprint.md: Imprint\n"
        sampleConfig += "04-chapter1.md: Chaper 1\n"
        sampleConfig += "05-chapter2.md: Chapter 2\n"
        sampleConfig += "\n"
        sampleConfig += "# An optional filename for the epub-file generated by \(executableName)\n"
        sampleConfig += "epub-filename: Ted Tester - The Title Of The Book.epub\n"
        
        return sampleConfig
    }
    
    
    
    
    
    // MARK: - Private
    
    func process(configDictionary: [String: String]) {
        if let author = configDictionary["author"] {
            self.author = author
        }
        
        if let title = configDictionary["title"] {
            self.title = title
        }
        
        if let description = configDictionary["description"] {
            self.bookDescription = description
        }
        
        if let language = configDictionary["language"] {
            self.language = language
        }
        
        if let copyright = configDictionary["copyright"] {
            self.copyright = copyright
        }
        
        if let date = configDictionary["date"] {
            self.date = date
        }
        
        if let identifier = configDictionary["identifier"] {
            self.identifier = identifier
        }
        
        if let cover = configDictionary["cover"] {
            self.coverImageFilePath = cover
        }
        
        if let style = configDictionary["style"] {
            self.style = style
        }
        
        if let epubFilename = configDictionary["epub-filename"] {
            self.epubFilename = epubFilename
        }
        
        configDictionary.keys.forEach { (key) in
            if key.hasSuffix(".\(FileExtensions.xhtml)") || key.hasSuffix(".\(FileExtensions.md)") {
                self.tocEntries.updateValue(configDictionary[key]!, forKey: key)
            }
        }
    }
    
    
    
    
    
    // MARK: - CustomStringConvertible
    public var description: String {
        get {
            return "Config:\n" +
                "    author: \"\(author)\"\n" +
                "    title: \"\(title)\"\n" +
                "    description: \"\(bookDescription)\"\n" +
                "    language: \"\(language)\"\n" +
                "    copyright: \"\(copyright)\"\n" +
                "    date: \"\(date)\"\n" +
                "    identifier: \"\(identifier)\"\n" +
                "    cover: \"\(coverImageFilePath)\"\n" +
                "    style: \"\(style ?? "<not configured>")" +
                tocEntries.reduce("    tocEntries:\n") { (current, element: (key: String, value: String)) -> String in
                    return current + "        \(element.key): \(element.value)\n"
            }
        }
    }
    
    // MARK: - CustomDebugStringConvertible
    public var debugDescription: String {
        get {
            return "Config:\n" +
                "    author: \"\(author)\"\n" +
                "    title: \"\(title)\"\n" +
                "    description: \"\(bookDescription)\"\n" +
                "    language: \"\(language)\"\n" +
                "    copyright: \"\(copyright)\"\n" +
                "    date: \"\(date)\"\n" +
                "    identifier: \"\(identifier)\"\n" +
                "    cover: \"\(coverImageFilePath)\"\n" +
                "    style: \"\(style ?? "<not configured>")" +
                tocEntries.reduce("    tocEntries:\n") { (current, element: (key: String, value: String)) -> String in
                    return current + "        \(element.key): \(element.value)\n"
            }
        }
    }
}






























